### ISSUE TITLE
GetEntities: "Path not rooted" exception

### ISSUE THREAD

**Issue by blachniet** [FrozenCow/sharpfilesystem#2]
When executing the code below with [this zip](https://drive.google.com/file/d/0B4yicvO2iYQDNEQ5X0Q0dUhzVWs/view?usp=sharing), I get a `ParseException` ("Path is not rooted") from [`FileSystemPath.Parse`](https://github.com/FrozenCow/sharpfilesystem/blob/master/SharpFileSystem/FileSystemPath.cs#L89). Am I using it wrong, or is this a bug?
 
``` c#
        static void Main(string[] args)
        {
            using (var stream = System.IO.File.OpenRead("sample.zip"))
            using (var fs = SharpFileSystem.SharpZipLib.SharpZipLibFileSystem.Open(stream))
            {
                foreach (var e in fs.GetEntities(FileSystemPath.Root))
                {
                    Console.WriteLine(e.EntityName + " - " + e.Path);
                }
            }
            Console.ReadKey();
        }


```

**Comment by FrozenCow** [comment]
SharpZipLibFileSystem has not been used for quite a while. I've just pushed a number of unit tests, that cover your problem and fixed the problem in SharpZipLibFileSystem. Please close this issue if this fixes your problem as well.

**Comment by blachniet** [comment]
I'm sorry it took me so long to respond. The latest code is working great for me. Thanks!
